### ISSUE TITLE
SSH problem : Connexion refused

### ISSUE THREAD

**Issue by BlackPearl01** [JMSDOnline/quick-box#12]
Hello,

I try to connect in SSH on QuickBox with Putty (on the 4747 port). But I have an error : "Connexion refused".

What is the package used by QuickBox ? Thanks !

**Comment by JMSDOnline** [comment]
Interesting. This is the tidbit that makes the adjustment...

```
  if [[ -e /etc/ssh/sshd_config ]]; then
    echo "Port 4747" /etc/ssh/sshd_config
    sed -i 's/Port 22/Port 4747/g' /etc/ssh/sshd_config
    service sshd restart >>"${OUTTO}" 2>&1
  fi
```

It will change this for root as well as your master (sudoer) account. It additionally restarts the ssh service on script completion.

Can you still access it on port 22?
...or is ssh completely knickered?

**Comment by BlackPearl01** [comment]
Same error on the port 22 :(

**Comment by JMSDOnline** [comment]
Do you have a means to attempt logging into the server by way of a vpn?

Or - we can test my theory and you can email me the IP... no need for username or password... just to see if I can connect. It may had happened that fail2ban blocked your own IP, however, it should automatically whitelist you.

**Comment by BlackPearl01** [comment]
I can try with a VPN if you want, but actually I try to access to my QuickBox in SSH with a Ubuntu Desktop (in the same network).

I have installed openssh-server package. And now, when I write "service sshd restart", I don't have any error (but same error with Putty on port 22 and 4747).

**Comment by JMSDOnline** [comment]
Yeah, I did not include openssh-server in my package list as I assume if you're connecting via shh to install the script, your server should already be running it by default. Most providers have the package installed while installing the image on the server.

If you are attempting as root, could you manage to do root from  Ubuntu desktop shell and then change your root password, followed by restarting ssh, then see if putty let's you in.

**Comment by BlackPearl01** [comment]
Yes, it's my fault, during the installation steps I don't have checked the openssh-server installation...

I have installed the package manually and I have changed the port number to 4747. After a restart, I don't have the "Connexion refused" but "Timed out"... I don't understand why !

**Comment by JMSDOnline** [comment]
Ah, are you building this from an image on ESXi?

**Comment by BlackPearl01** [comment]
Yes... and in the same time which I read your answer ... I have watched my configuration in my ESXi firewall and I authorized the SSH connexion.. It's OK now :)

Thanks !

**Comment by JMSDOnline** [comment]
Ding Ding! That's exactly what I was going to suggest. Glad you got it my friend. I'm here if you need me. 

PS: I added the package in just in case others build their own.

**Comment by BlackPearl01** [comment]
Perfect !
