### ISSUE TITLE
Update Btsync

### ISSUE THREAD

**Issue by piluc88** [JMSDOnline/quick-box#15]
Hello what is the best way to update btsync??

**Comment by JMSDOnline** [comment]
It looks like the version available is for the desktop app that syncs with your server... not really the server install.

**Comment by JMSDOnline** [comment]
I'll work on a script however that pulls and builds a new version on top of the installed version. This should just write it as an update and not overwrite any settings.

**Comment by piluc88** [comment]
OK thanks you for your quick anwser

**Comment by JMSDOnline** [comment]
@piluc88 
Added a script to upgrade BTSync in accordance with the way Quick Box is built. The installation method I wrote for BTSync is not a typical installation.

Install instructions can be found here:
[Update for BTSync - grabs latest addition](https://github.com/JMSDOnline/quick-box#update-for-btsync---grabs-latest-addition)

For topic's sake I will post those instructions here:

Run the following command to grab our command for updating ...
```
curl -LO https://raw.githubusercontent.com/JMSDOnline/quick-box/master/qb-pck-upgrades.sh

```
... Finally, make the script executable and run to produce the updates ...
```
chmod +x qb-pck-upgrades.sh
./qb-pck-upgrades.sh

```

##### In the future, after downloading this script, you can simply type 'upgradeBTSync' to upgrade.
