### ISSUE TITLE
Supported OS

### ISSUE THREAD

**Issue by nilimahona** [JMSDOnline/quick-box#2]
Does it only support Ubuntu 15?
I have a dedi server where i want to use it but it have ubuntu 12.04 installed. does it work?

**Comment by JMSDOnline** [comment]
It should work on Ubuntu 12.x and up. I tested it on 14.04 | 15.04 | 15.10 without issues. I will run some additional tests today or tomorrow and update the readme according to what I find.

**Comment by nilimahona** [comment]
Thnaks. I'll try the script tonight and i'll try to write a description.

**Comment by JMSDOnline** [comment]
I just ran a quick test. It fails to build apache at the moment. I will work on that shortly.

**Comment by nilimahona** [comment]
which version of ubuntu?

**Comment by JMSDOnline** [comment]
12.04 x64

**Comment by nilimahona** [comment]
can you assure it works on 14.04?

**Comment by JMSDOnline** [comment]
I am testing that right now as well.. the installation of rtorrent and libtorrent went rather fast which tells me it's a fail on that release as well.

**Comment by JMSDOnline** [comment]
In 14.04 and 12.04 the libcurl4-openssl-dev dependency needs another method. Fixing now and thne the test should pass on both 12.04 and 14.04 releases.

**Comment by nilimahona** [comment]
Thanks. please leave a comment here when it's fixed. i can't wait to try.

**Comment by JMSDOnline** [comment]
I shall. The badges in the repo will update also :) . Thanks for giving it a whirl.

**Comment by nilimahona** [comment]
and i must say your script and theme looks great. i used notos script and danny's script but after a certain time with the messy big codes the seedbox fails. if you can keep it stable and upgraded you'll be helping many noobs and seedbox users. thanks again for making this script.

**Comment by JMSDOnline** [comment]
@nilimahona 
14.04 is now passing all tests.

You can see the new installation instructions on the quick-box/readme.md

As per 12.04. The readme has an additional status update in this regards. I will not be adding in 12.04 support for Quick Box.

**Comment by nilimahona** [comment]
i can not install. can i have your mail address?
