### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by nilimahona** [JMSDOnline/quick-box#3]
I tried to install in ubuntu 14.04. i think there is something with permissions.

i ran the commnad with sudo ./quickbox-14x.sh
script also says Congrats! You're running as root. Let's continue

after that Installing building tools and all dependancies and perl modules, please wait ...
here started the error tar.... rar,,,,,

then i choose rtorrent and other options but log kept saying error file read only etc etc. 
i think the script doesn't run as root fully. it just start as a root maybe

PS: i write this whole thing because after completion the whole install i tried to access the log file but it was empty(because it can't write during installation,said read only)and no rutorrent or anything.

*** Please add a to the description that this will change the port to 4747

**Comment by JMSDOnline** [comment]
After the install port 4747 shows as well as where the login info is contained. It's in the finishing of the script. I do plan on adding in more concrete details once I have more time on my hands. 

In regards to your fail on install, there should be no permissions errors as you are installing as root. 

What provider/hardware are you installing on.. and are you doing this on a fresh install?

**Comment by nilimahona** [comment]
I use one provider. as u know they don't offer ubuntu 14.04 directly i installed 12.04 and update it then reboot and then run the commands with sudo. may be it's my mistake but i'll appriciate very much to install this. please give me your mail address sir.

**Comment by JMSDOnline** [comment]
Ah, actually. I would suggest this. Open a ticket with them and ask that they install an Ubuntu 15.04 or 15.10 image. They have them available, they just don't list them for some reason. I have not attempted to run the script on a box after updating via 'dist-upgrade'. Also... yes... the script should be ran as full root.

Ask them for a quick reinstall (weekend at OP so it may be slow) and I will kindly install this for you.

My email is jmsolodesigns[at]gmail[dot]com

**Comment by nilimahona** [comment]
i told them many times and they are saying they are having problems instaliing ubuntu 15. and now i've to use notos script because i really need the box ready. also OP does not provide actual root account u know. best will be if u make a video tutorial. i'll try in a vbox then if ok i'll reinstall it. don't forget to check your email

**Comment by JMSDOnline** [comment]
In 15.x you have to modify the sshd_config to allow root. Once you get the box I can make all the needed enhancements for you (I don't mind doing this on slow days). I have my box actually on 15.x at OP... don't let them get lazy on you.

**Comment by nilimahona** [comment]
Thanks.

**Comment by nilimahona** [comment]
Thanks. i'd love to. i send mail. please check.
