### ISSUE TITLE
Debian compatibility 

### ISSUE THREAD

**Issue by Angristan** [JMSDOnline/quick-box#4]
Hello, does it work with Debian ? And which version of Ubuntu do you recommend ? :)

**Comment by JMSDOnline** [comment]
@Angristan 
I would recommend using on either 15.04 or 15.10 of Ubuntu as those are the initial releases I crafted Quick Box on.

As per Debian compatibility... I am actually working on a Debian 7 and 8 version of Quick Box. I have no ETA on it's release at this moment, however, it shouldn't be more than a couple of weeks from now.

**Comment by Angristan** [comment]
That's pretty cool, thank you.

**Comment by JMSDOnline** [comment]
Debian 7 & 8 are now Quick Box compatible
