### ISSUE TITLE
No web interface

### ISSUE THREAD

**Issue by Angristan** [JMSDOnline/quick-box#5]
After running the script and rebooting on Ubuntu 14.04, I have nothing that listens to :80 
```
root@biggie ~# netstat -tlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 localhost.localdo:49631 *:*                     LISTEN      686/Plex Plug-in [c
tcp        0      0 localhost.localdo:33224 *:*                     LISTEN      943/Plex Plug-in [c
tcp        0      0 localhost.localdo:38920 *:*                     LISTEN      636/Plex Plug-in [c
tcp        0      0 localhost.localdo:44169 *:*                     LISTEN      866/Plex Plug-in [c
tcp        0      0 *:4747                  *:*                     LISTEN      386/sshd
tcp        0      0 *:32400                 *:*                     LISTEN      521/Plex Media Serv
tcp        0      0 localhost.localdo:32401 *:*                     LISTEN      521/Plex Media Serv
tcp        0      0 *:32469                 *:*                     LISTEN      573/Plex DLNA Serve
tcp        0      0 localhost.locald:domain *:*                     LISTEN      439/unbound
tcp        0      0 localhost.localdom:8953 *:*                     LISTEN      439/unbound
tcp        0      0 *:1883                  *:*                     LISTEN      573/Plex DLNA Serve
tcp        0      0 localhost.localdo:36380 *:*                     LISTEN      530/Plex Plug-in [c
tcp        0      0 localhost.localdo:52285 *:*                     LISTEN      919/Plex Plug-in [c
tcp        0      0 localhost.localdo:49693 *:*                     LISTEN      710/Plex Plug-in [c
tcp        0      0 *:5757                  *:*                     LISTEN      293/vsftpd

tcp6       0      0 [::]:4747               [::]:*                  LISTEN      386/sshd
tcp6       0      0 localhost:8953          [::]:*                  LISTEN      439/unbound
```

**Comment by JMSDOnline** [comment]
Interesting. I have to ask.

1. Did you install on a fresh server?
2. Did you use the 14x.sh install script?
3. VPS/Dedicated
4. Provider

**Comment by Angristan** [comment]
1. Yep
2. Yep
3. OpenVZ VPS
4. PulseHeberg

Btw, I get this : `Cannot execute /usr/bin/lshell: No such file or directory`
Also, how to use commands like restartSeedbox ?

**Comment by JMSDOnline** [comment]
When are you getting the lshell error? As an original (master) account you should not be seeing any reference to lshell as that is not used until the creation of another user.

Per the commands:
https://github.com/JMSDOnline/quick-box/wiki/F.A.Q#i-typed-setdisk-but-i-get-a-permissions-error

You will need to first reboot in order for the commands in the bashrc profile to go into effect.

If you try to restart apache, does it restart, or does it inform you it's not installed?

**Comment by JMSDOnline** [comment]
I am thinking that OpenVZ may be what's causing an issue... I have only tested thoroughly on KVM and dedicated servers. But I need to investigate this further... I appreciate your continued reports.

**Comment by Angristan** [comment]
I only get this if I enter 
```
root@biggie ~# su angristan
Cannot execute /usr/bin/lshell: No such file or directory
```
Well I rebooted and it does not work either : 
```
[root@biggie]:(360.3kb)~# restartSeedbox
bash: restartSeedbox: command not found
```
And for apache : 
```
[root@biggie]:(360.3kb)~# service apache restart
apache: unrecognized service
```

**Comment by Angristan** [comment]
OK, if you need more reports, no problem.

**Comment by JMSDOnline** [comment]
When you got the question:

"Set user shell to lshell?" did you select yes or no.

It looks like you added your master account to the limited shell, which then failed to install the needed aspects of the script.

**Comment by Angristan** [comment]
I selected yes, and at this moment I was running as root into the fish shell

**Comment by JMSDOnline** [comment]
That is the problem then.

See:
https://github.com/JMSDOnline/quick-box/wiki/F.A.Q#the-script-on-install-asks-me-if-i-want-to-set-my-user-to-lshell-what-should-i-answer

You're installing as root yes... but you need to create the initial master account. The first original account should not go to the limited shell as it's the "sudoer" building the needed services.

**Comment by Angristan** [comment]
So I should answer no ?

**Comment by JMSDOnline** [comment]
Correct. Just stick with the default, which is No. I should more than likely just remove this from the prompt to avoid any confusions.

**Comment by JMSDOnline** [comment]
@Angristan 
I found a massive issue that could very well be preventing the positive build for you. I tested the script on a borrowed OpenVZ VM and sure enough... the script fails. It was attempting to perform an impossible update due to a conflicting source. This was a huge oversight on my part. I will be updating the script here shortly.

**Comment by Angristan** [comment]
Ok ! May I test again ?

**Comment by JMSDOnline** [comment]
@Angristan, yes, please do.

**Comment by Angristan** [comment]
It works \o/

**Comment by Angristan** [comment]
Little bug ? http://i.imgur.com/Y3Xzmlu.png

**Comment by JMSDOnline** [comment]
Check this out:
https://github.com/JMSDOnline/quick-box/wiki/F.A.Q#my-disk-space-shows-as-00009-or-negative-something-other-on-the-dashboard

**Comment by Angristan** [comment]
Fixed, thanks !

**Comment by JMSDOnline** [comment]
Yup. Just shout in a new issue if anything pops up. Closing this one.. and thanks for your patience @Angristan !

**Comment by Angristan** [comment]
No problem :)
