### ISSUE TITLE
Updating quick-box

### ISSUE THREAD

**Issue by Angristan** [JMSDOnline/quick-box#6]
Hi again, is there any way to update quick-box ? I see you are making a lot of changes.

**Comment by JMSDOnline** [comment]
As per the changes at this moment they are rather small. In the future
after the changelog has grown to the need for version updates, I do plan on
writing an update script to go from version to version on live servers
without interfering with it's current running features.

As per bringing these changes over to you now. Let me compile a list here
in the next day or so and I will send them over to you. Simple command-line
based enhancements.


Regards,

*Jason Matthews,*Designer - Developer

JMSolo Designs | Creative Web Design & Development
PO Box 3703, S Padre Isle, TX 78597 tel. + 1 956 299 4231
<+%201%20956%20299%204231>
www.jmsolodesigns.com <https://jmsolodesigns.com/>
<https://www.facebook.com/JMSoloDesigns>
<https://twitter.com/JMSoloDesigns>  [image: http://is.gd/OZYK3W]
<http://is.gd/OZYK3W>

**Comment by Angristan** [comment]
All right, thank you. :)

**Comment by BlackPearl01** [comment]
Thanks ! :+1:

**Comment by JMSDOnline** [comment]
[Quick Box v1.3 Changelog](https://github.com/JMSDOnline/quick-box-update/blob/master/v1-3/changelog.md)

Updating via the script is fairly simple and straightforward. Tested a few dozen times and nothing broke. Just ensure you keep backups of any files... however, in this critical update... nothing is really going to be overwritten.

[Update to Quick Box version 1.3](https://github.com/JMSDOnline/quick-box#update-to-quick-box-version-13)

...and this is how we update. At least until I get really bored during work and decide to write an API and link to an update server.

**Comment by JMSDOnline** [comment]
Yes, I just addressed a few issues that the updater had. 

You can run the update script over the top of you install once more and it will fix what it must. 

That error in particular was a result of trying to move a file that had already been modified in a command directly above it.
