### ISSUE TITLE
No access on SSH with 4747

### ISSUE THREAD

**Issue by bilyboy785** [JMSDOnline/quick-box#8]
Hi, i can't connect to my server with SSH on 4747.. No response. And Plex dont works.
Have u got any idea ?

**Comment by JMSDOnline** [comment]
Please provide more details.

1. Did you install the script on a fresh server
2. What Ubuntu Release are you using
2. Did you reboot after completion
3. Did you opt to install Plex
4. Did you install your first initial user in LShell (as this would break your install - LShell is for secondary users)

You may also got to your /root/ directory and copy and paste the output of 'quick-box.log' to pastebin and share back with me the link.

The more details you provide the more I can help as this is a first.

**Comment by bilyboy785** [comment]
I installed it on a 15.10 64Bits, a fresh server and i reboot after installation.
I opt to install Plex, but it's not Plex server ? I can't add library.. 

I think problem come from first initial user like you said ;) I will restart it.

**Comment by JMSDOnline** [comment]
Thank you for the feedback. Someone selecting Yes to LShell their initial user isn't the first time. I think in the next release of the script (today or tomorrow - time permitted) I will remove this option.

**Comment by bilyboy785** [comment]
Thank's for this awesome support ! I retest. But i've another question, in plex, why we can't add library ?

**Comment by JMSDOnline** [comment]
Plex initially has been built from a package rather than pulled from a ppa... however, I am currently working on a fix for this due to my oversight that debian sources can, in fact, work with Ubuntu. I am building the option to make plex live and public (switch on) without the need for a tunnel on port 34100. Then Plex will be made private (requiring typical plex login screen and ssh tunnel) (switch off). Then, the libraries will work better. 

You should however be able to add a library for your main account. I would need more info as I have been able to add them in my trials. Is there any particular error that comes up?

**Comment by bilyboy785** [comment]
No error, just, when i start Plex, and it ask me an account so i enter my credentials and it just show me my other Plex server and libraries. So it's just a player, this is the reason why i ask you this. It's not usefull on a server :) But good Job for the rest.

I have make another test and i leave the option on No for shell, but after restart, i access to the web interface but not on SSH (4747, 22).. I don't understand :(

**Comment by JMSDOnline** [comment]
You must create an SSH Tunnel for the server to show up on your account.

**Comment by JMSDOnline** [comment]
Are you attempting to connect with your sudo user you created during script installation, or with root?

**Comment by bilyboy785** [comment]
I just launch Putty, with IP and Port 4747. I can't find the way to make a tunnel with Putty :(

**Comment by JMSDOnline** [comment]
There are a few guides around the wilds of the internet:
http://n00tz.net/2013/09/quick-tip-ssh-tunneling/ 

That one is fairly easy to follow

**Comment by JMSDOnline** [comment]
I created an additional F.A.Q. guide: [How do I create an SSH Tunnel and connect to Plex?](https://github.com/JMSDOnline/quick-box/wiki/F.A.Q#how-do-i-create-an-ssh-tunnel-and-connect-to-plex). That is more representative of the Quick Box install. Any additional questions I will help (time permitting)

**Comment by bilyboy785** [comment]
All is OKKKKK ! Love U, Love your work ! Thank's a lot guy !

**Comment by JMSDOnline** [comment]
\o/ Huzzah! Thank you so much for the kind words. Do enjoy and be sure to stay tuned for future updates.
